version: '1.0'
services:
  monguito:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alemol
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db